using System;
using System.ComponentModel;

namespace TWallet.Util
{
    public enum CurrencySymbolEnum
    {
        [Description("A$")]
		AUD,
        [Description("лв.")]
        BGN, 
        [Description("R$")]
        BRL,
        [Description("C$")]
        CAD,
        [Description("CHF")]
        CHF,
        [Description("¥")]
		CNY,
        [Description("Kč")] 
        CZK,
        [Description("kr.")] 
        DKK,
        [Description("£")] 
        GBP,
        [Description("HK$")] 
        HKD,
        [Description("kn")]
		HRK,
        [Description("Ft")] 
        HUF,
        [Description("Rp")] 
        IDR,
        [Description("₪")] 
        ILS,
        [Description("₹")] 
        INR,
        [Description("円")]
	    JPY, 
        [Description("‎₩")] 
        KRW,
        [Description("MXN$")] 
        MXN,
        [Description("M$")] 
        MYR, 
        [Description("kr")] 
        NOK,
        [Description("NZD$")]
		NZD,
        [Description("PHP")] 
        PHP,
        [Description("zł")] 
        PLN,
        [Description("L")] 
        RON,
        [Description("руб")] 
        RUB,
		[Description("kr")] 
        SEK,
        [Description("S$")] 
        SGD,
        [Description("฿")] 
        THB,
        [Description("‎₺")] 
        TRY,
        [Description("$")] 
        USD,
		[Description("R")] 
        ZAR,
        [Description("€")] 
        EUR
    }
}
